name: storm_kit
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.8.19
  - zlib
  - zeromq
  - yaml
  - xz
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxdmcp
  - xorg-libxau
  - xorg-libx11
  - xorg-libsm
  - xorg-libice
  - tk
  - tornado
  - scipy
  - setuptools
  - readline
  # - pytorch=2.3.0 - install manually after you run prune with gpu configiration from reame instructions. go to pytorch.com for help
  - cudatoolkit=11.8
  # - cudatoolkit=12.1
  - numpy
  - scikit-learn
  - matplotlib
  - quaternion
  - pip
  - pip:
    - yacs==0.1.8
    - urdfpy==0.0.22
    - urdf-parser-py==0.0.4
    - torchvision==0.18.0
    - torchaudio==2.3.0
    - trimesh==4.4.0
    - traitlets==5.14.3
    - tqdm==4.66.4
    - werkzeug==3.0.3
    - widgetsnbextension==4.0.10
    - wheel==0.43.0
    - wcwidth==0.2.13
    - urdfpy==0.0.22
    - urdf-parser-py==0.0.4
    - typing_extensions==4.11.0
    - tenacity==8.3.0
    - tabulate==0.9.0
    - sympy==1.12
    - stack-data==0.6.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinx-rtd-theme==2.0.0
    - sphinx-autodoc-annotation==1.0.post1
    - sphinx==7.1.2
    - snowballstemmer==2.2.0
    - sk-video==1.1.10
    - six==1.16.0
    - sip==6.7.12
    - setuptools==69.5.1
    - scikit-learn==1.3.2
    - rpds-py==0.18.1
    - retrying==1.3.4
    - requests==2.31.0
    - referencing==0.35.1
    - pyzmq==26.0.3
    - pyyaml==6.0.1
    - pytorch3d==0.3.0
    # - python-tzdata==2024.1
    - python-dateutil==2.9.0
    - pytest==8.2.0
    - pysocks==1.7.1
    - pyrender==0.1.45
    - pyquaternion==0.9.9
    # - pyqt5-sip==12.12.2
    # - pyqt==5.15.9
    - pyparsing==3.1.2
    - pyopengl==3.1.0
    - pygments==2.18.0
    - pyglet==2.0.15
    - pycollada==0.6
    - pure-eval==0.2.2
    # - pulseaudio-client==17.0
    - ptyprocess==0.7.0
    - prompt-toolkit==3.0.43
    - portalocker==2.8.2
    - pooch==1.8.1
    - ply==3.11
    - pluggy==1.5.0
    - plotly==5.22.0
    - platformdirs==4.2.2
    # - pixman==0.43.2
    - pip==24.0
    - pillow==10.3.0
    - pickleshare==0.7.5
    - pexpect==4.9.0
    # - pcre2==10.43
    - parso==0.8.4
    - packaging==24.0
    - opencv-python==4.9.0.80
    - open3d==0.18.0
    - omegaconf==2.3.0
    - jsonschema-specifications==2023.12.1
    - jsonschema==4.22.0
    - joblib==1.4.2
    - jupyterlab-widgets==3.0.10
    - jupyter-core==5.7.2
    - ipywidgets==8.1.2
    - ipython==8.12.3
    - iopath==0.1.10
    - importlib_resources==6.4.0
    - importlib-resources==6.4.0
    - importlib-metadata==7.1.0
    - imagesize==1.4.1
    - imageio-ffmpeg==0.4.9
    - imageio==2.34.1
    - idna==3.7
    - hydra-core==1.3.2
    - ghalton==0.6.2
    - fvcore==0.1.5.post20221221
    - fsspec==2024.5.0
    - freetype-py==2.4.0
    - flask==3.0.3
    - fastjsonschema==2.19.1
    - exceptiongroup==1.2.0
    - docutils==0.20.1
    - decorator==5.1.1
    - dash-table==5.0.0
    - dash-html-components==2.0.0
    - dash-core-components==2.0.0
    - dash==2.17.0
    - configargparse==1.7
    - colorlog==6.8.2
    - cloudpickle==3.0.0
    - click==8.1.7
    - charset-normalizer==3.3.2
    - blinker==1.8.2
    - backcall==0.2.0
    - babel==2.15.0
    - austin==2016.0.1
    - attrs==23.2.0
    - storm-kit
    - isaacgym==1.0rc4
    # - - e Stoix/requirements/requirements.txt    
    # - -r file:Stoix/requirements/requirements.txt
    # - -r file:Stoix/requirements/requirements-dev.txt

