
world_model:
  coll_objs:
    sphere:
      sphere1: # 
        radius: 0.15 # meters
        position: [0.3, 0.3, 0.35]
      sphere2: # 
        radius: 0.15 # meters
        position: [0.3, -0.3, 0.25]
      # sphere3: # 
      #   radius: 0.15 # meters
      #   position: [-0.3, -0.3, 0.3]
      # sphere4:
      #   radius: 0.05 # meters
      #   position: [0.0, 0.04, 0.0]
      # sphere5:
      #   radius: 0.06 # meters
      #   position: [0.0, 0.0, 0.0]
      # sphere6:
      #   radius: 0.07 # meters
      #   position: [0.0, 0.0, 0.0]
      # sphere7:
      #   radius: 0.07 # meters
      #   position: [0.0, 0.0, 0.0]
      # sphere8:
      #   radius: 0.08 # meters
      #   position: [0.0, 0.0, 0.0]
      # sphere9:
      #   radius: 0.09 # meters
      #   position: [0.0, 0.0, 0.0]
      # sphere10:
      #   radius: 0.1 # meters
      #   position: [0.0, 0.0, 0.0]

    cube:
      cube1:
        dims: [0.1, 0.2, 0.2]
        pose: [-2, 0.2, 0.3, 0.4, 0.5, 0.3, 1.0]
      cube2:
        dims: [0.1, 0.1, 1.2]
        pose: [2.3, 2.2, 2.3, 0.4, 0.5, 2.3, 1.0]
      cube3:
        dims: [0.1, 0.1, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube4:
        dims: [0.1, 0.2, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube5:
        dims: [0.1, 0.2, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube6:
        dims: [0.1, 0.2, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube7:
        dims: [0.1, 0.3, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube8:
        dims: [0.1, 0.3, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube9:
        dims: [0.1, 0.3, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube10:
        dims: [0.2, 0.1, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube11: #
        dims: [0.5, 0.5, 0.5]
        pose: [0, 0, 0, 0, 0, 0, 0]
      cube12: # 
        dims: [0.2, 0.1, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube13: # 
        dims: [0.2, 0.2, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube14:
        dims: [0.2, 0.2, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube15:
        dims: [0.2, 0.2, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube16:
        dims: [0.2, 0.3, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube17:
        dims: [0.2, 0.3, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube18:
        dims: [0.2, 0.3, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube19:
        dims: [0.3, 0.1, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube20:
        dims: [0.3, 0.1, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube21:
        dims: [0.3, 0.1, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube22:
        dims: [0.3, 0.2, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube23:
        dims: [0.3, 0.2, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube24:
        dims: [0.3, 0.2, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube25:
        dims: [0.3, 0.3, 0.1]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube26:
        dims: [0.3, 0.3, 0.2]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube27:
        dims: [0.3, 0.3, 0.3]
        pose: [0.0, 0.0, 0.0, 0, 0, 0, 1.0]
      cube28:
        dims: [2.0, 2.0, 0.2] # x, y, z
        pose: [0.0, 0.0, -0.1, 0, 0, 0, 1.0] # x, y, z, qx, qy, qz, qw

