
world_model:
  coll_objs:
    cube:
      cube1: # the table under the base
        dims: [2.0, 2.0, 0.2] # x, y, z
        pose: [0.0, 0.0, -0.1, 0, 0, 0, 1.0] # x, y, z, qx, qy, qz, qw
      
      cube2:
        dims: [0.1, 0.02, 0.1] # flat square plate
        pose: [0.4, 0.4, 0.5, 1, 1, 1, 3] # left,
      
      cube3:
        dims: [0.1, 0.02, 0.1] # flat square plate
        pose: [0.3, 0.3, 0.5, 1, 1, 1, 3] # left,
      
      # cube4:
      #   dims: [0.1, 0.02, 0.1] # flat square plate
      #   pose: [0.3, 0.3, 0.4, 1, -1, -2, 3] # left,

    sphere:
      sphere1:  
        radius: 0.02 # meters
        position: [-3, -3, -3] 
    #   sphere2: # 
    #     radius: 0.02 # meters
    #     position: [-0.40, 0.45, 0.5]

    #   sphere3: # 
    #     radius: 0.03 # meters
    #     position: [-0.35, 0.25, 0.5]
        
    #   # sphere3: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.5, 0.5, 0.3]
    #   # sphere4: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.3, 0.35, 0.2]
    #   # sphere5: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.2, 0.55, 0.3]
    #   # sphere6: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.3, -0.3, -0.25]
    #   # sphere7: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.3, 0.3, 0.35]
    #   # sphere8: # 
    #   #   radius: 0.05 # meters
    #   #   position: [0.3, -0.3, 0.25]

 
    # cube:
      