##
## MIT License
##
## Copyright (c) 2020-2021 NVIDIA CORPORATION.
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.##
world_model:
  coll_objs:
    sphere:
      sphere1:
        radius: 0.04 # meters
        position: [0.0, 3.0, 0.0]
      sphere2:
        radius: 0.04 # meters
        position: [0.0, 3.0, 0.0]
      sphere3:
        radius: 0.04 # meters
        position: [0.0, 3.0, 0.0]
      sphere4:
        radius: 0.05 # meters
        position: [0.0, 3.0, 0.0]
      sphere5:
        radius: 0.06 # meters
        position: [0.0, 3.0, 0.0]
      sphere6:
        radius: 0.07 # meters
        position: [0.0, 3.0, 0.0]
      sphere7:
        radius: 0.07 # meters
        position: [0.0, 3.0, 0.0]
      sphere8:
        radius: 0.08 # meters
        position: [0.0, 3.0, 0.0]
      sphere9:
        radius: 0.09 # meters
        position: [0.0, 3.0, 0.0]
      sphere10:
        radius: 0.1 # meters
        position: [0.0, 3.0, 0.0]

    cube:
      cube1:
        dims: [0.1, 0.1, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube2:
        dims: [0.1, 0.1, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube3:
        dims: [0.1, 0.1, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube4:
        dims: [0.1, 0.2, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube5:
        dims: [0.1, 0.2, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube6:
        dims: [0.1, 0.2, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube7:
        dims: [0.1, 0.3, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube8:
        dims: [0.1, 0.3, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube9:
        dims: [0.1, 0.3, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube10:
        dims: [0.2, 0.1, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube11:
        dims: [0.2, 0.1, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube12:
        dims: [0.2, 0.1, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube13:
        dims: [0.2, 0.2, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube14:
        dims: [0.2, 0.2, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube15:
        dims: [0.2, 0.2, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube16:
        dims: [0.2, 0.3, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube17:
        dims: [0.2, 0.3, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube18:
        dims: [0.2, 0.3, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube19:
        dims: [0.3, 0.1, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube20:
        dims: [0.3, 0.1, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube21:
        dims: [0.3, 0.1, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube22:
        dims: [0.3, 0.2, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube23:
        dims: [0.3, 0.2, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube24:
        dims: [0.3, 0.2, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube25:
        dims: [0.3, 0.3, 0.1]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube26:
        dims: [0.3, 0.3, 0.2]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube27:
        dims: [0.3, 0.3, 0.3]
        pose: [0.0, 3.0, 0.0, 0, 0, 0, 1.0]
      cube28:
        dims: [2.0, 2.0, 0.2] # x, y, z
        pose: [0.0, 0.0, -0.1, 0, 0, 0, 1.0] # x, y, z, qx, qy, qz, qw

